### ISSUE TITLE
[Healer Layout] Debuffs on target frame

### ISSUE THREAD

**Issue by Neiara** [Solor/FreeUI_Classic#19]
Option to only show your own debuffs on the target frame when using the healer layout. If it exceeds more than one line, it goes over the actual health frames of the raid, making it impossible to heal a couple of people.

Edit: You can also just come up with a solution so the debuffs on the target frame do not overlap with the raid health bars.

**Comment by fafaraway** [comment]
with new update, target auras moved to the top
also, you can try only show debuffs that created by you via config panel
