### ISSUE TITLE
[Question] How to move Unit Frames Buffs/Debuffs

### ISSUE THREAD

**Issue by ihme** [Solor/FreeUI_Classic#9]
With one of the newer updates, the buffs/debuffs position on my target has moved from TOPLEFT to BOTTOMRIGHT. I cannot find the correct LUA to edit to move it back myself. Any assistance would be greatly appreciated.

**Comment by fafaraway** [comment]
https://github.com/Solor/FreeUI_Classic/blob/master/FreeUI/scripts/unitframe/elements/auras.lua
line 196
